### ISSUE TITLE
Add page level component that would display the uploader

### ISSUE THREAD

**Issue by alexjoybc** [SierraSystems/secure-file-storage#7]
blocked by: #6

**Comment by adodge-bcg** [comment]
#5 #6 and this may all be solved by one component. The mds project uses a package called filepond (https://www.npmjs.com/package/filepond) which looks like it provides a UI component for dragging and dropping files, adding/removing files from the upload component, and displaying the list of files selected for upload. It also has a bunch of documentation on usage (https://pqina.nl/filepond/)

This is used in the FileUploader.js file which is called from FilePicker.js

**Comment by sdevalapurkar** [comment]
done in https://github.com/SierraSystems/secure-file-storage/pull/27
